
services:
  rig:
    image: "rlib/rig-builder:latest"
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep 100000d
    volumes:
      - type: bind
        source: .
        target: /work
      - type: volume
        source: cargo-cache
        target: /home/rigbuild/.cargo/registry
      - type: volume
        source: cargo-git
        target: /home/rigbuild/.cargo/git

volumes:
  cargo-cache:
  cargo-git:
