//! Dev-only build tasks for rig. Run with `cargo xtask <task>`.
//!
//! Tasks:
//!   gen-help            Regenerate src/help-generated.in from src/help/*.md
//!   gen-help --check    Verify src/help-generated.in is up to date (CI guard)
//!
//! The help prose for each command lives in `src/help/*.md`: the lead paragraph
//! (before the first heading) is the short `about`, and the rest is the long
//! `long_about`. `gen-help` renders each part to colored ANSI (see `render.rs`)
//! and writes them as `ABOUT_*` / `HELP_*` `&str` constants to the committed
//! `src/help-generated.in`, which `src/args.rs` includes into the `rig` binary.
//! `gen-help --check` instead verifies that the committed file still matches the
//! Markdown sources, so CI fails if someone edits a `.md` without regenerating.
//!
//! This crate is never part of the `rig` binary; it only runs when invoked
//! explicitly via `cargo xtask`.

mod render;

use std::fs;
use std::path::PathBuf;
use std::process::ExitCode;

use render::{md_to_ansi_impl, md_to_ansi_inline};

fn workspace_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("xtask crate has a parent directory")
        .to_path_buf()
}

fn help_dir() -> PathBuf {
    workspace_root().join("src/help")
}

fn generated_path() -> PathBuf {
    workspace_root().join("src/help-generated.in")
}

// `rtools-add` -> (`ABOUT_RTOOLS_ADD`, `HELP_RTOOLS_ADD`)
fn const_name(prefix: &str, stem: &str) -> String {
    format!("{}_{}", prefix, stem.replace('-', "_").to_uppercase())
}

// Split a help Markdown file into its short summary (`about`) and long help
// (`long_about`). The summary is the optional lead paragraph before the first
// ATX heading; the long help is everything from the first heading onward and is
// rendered exactly as before. Files with no lead (e.g. `about.md`,
// `examples.md`) yield an empty summary.
fn split_help(md: &str) -> (&str, &str) {
    match md
        .lines()
        .scan(0usize, |off, line| {
            let start = *off;
            *off += line.len() + 1;
            Some((start, line))
        })
        .find(|(_, line)| {
            let t = line.trim_start();
            t.starts_with('#') && t.trim_start_matches('#').starts_with(' ')
        }) {
        Some((start, _)) => (md[..start].trim(), &md[start..]),
        None => (md.trim(), ""),
    }
}

// Build the full contents of `src/help-generated.in` from `src/help/*.md`.
fn render_generated() -> String {
    let mut entries: Vec<PathBuf> = fs::read_dir(help_dir())
        .expect("read src/help")
        .map(|e| e.expect("dir entry").path())
        .filter(|p| p.extension().map(|e| e == "md").unwrap_or(false))
        .collect();
    entries.sort();

    let mut out = String::from(
        "// -*- mode: rust -*-\n\
         //\n\
         // Generated by `cargo xtask gen-help` (run `make help`). Do not edit by hand.\n\
         // The help text is written in Markdown in `src/help/*.md`: the lead\n\
         // paragraph is the short `about`, the rest is the long `long_about`.\n\n",
    );
    for path in entries {
        let stem = path.file_stem().unwrap().to_str().unwrap();
        let md = fs::read_to_string(&path).expect("read help md");
        let (about, long) = split_help(&md);
        if !about.is_empty() {
            let ansi = md_to_ansi_inline(about, true);
            out.push_str(&format!(
                "const {}: &str = {:?};\n",
                const_name("ABOUT", stem),
                ansi
            ));
        }
        if !long.is_empty() {
            let ansi = md_to_ansi_impl(long, true);
            out.push_str(&format!(
                "const {}: &str = {:?};\n",
                const_name("HELP", stem),
                ansi
            ));
        }
    }
    out
}

fn gen_help(check: bool) -> ExitCode {
    let generated = render_generated();
    let path = generated_path();
    if check {
        let committed = fs::read_to_string(&path).unwrap_or_default();
        if committed != generated {
            eprintln!(
                "error: {} is out of date with src/help/*.md; run `make help`",
                path.display()
            );
            return ExitCode::FAILURE;
        }
        eprintln!("{} is up to date", path.display());
    } else {
        fs::write(&path, &generated).expect("write help-generated.in");
        eprintln!("wrote {}", path.display());
    }
    ExitCode::SUCCESS
}

fn main() -> ExitCode {
    let args: Vec<String> = std::env::args().skip(1).collect();
    match args.first().map(String::as_str) {
        Some("gen-help") => {
            let check = args[1..].iter().any(|a| a == "--check");
            gen_help(check)
        }
        other => {
            eprintln!(
                "unknown task: {}\n\nUsage:\n  cargo xtask gen-help [--check]",
                other.unwrap_or("(none)")
            );
            ExitCode::FAILURE
        }
    }
}
