#!/usr/bin/env bash
#
# Generate the browsable command-line reference for the website.
#
# Runs the built `rig` binary and captures `--help` for every command and
# subcommand (recursively). It writes:
#
#   - one page per top-level command, website/reference/<cmd>.qmd, with the
#     command's help and a section for each of its subcommands (recursively);
#   - website/reference/_overview.md, the top-level `rig --help` output,
#     included by reference/index.qmd;
#   - website/reference/_toc.md, a linked list of the command pages, also
#     included by reference/index.qmd.
#
# The per-command pages and the two `_*.md` includes are generated; index.qmd
# is hand-written. Generated pages carry a marker comment and are removed and
# regenerated on every run, so commands that disappear leave no stale pages.
#
# Usage:
#   website/gen-cli-reference.sh [path-to-rig]
#
# If no path is given, target/release/rig is used (falling back to
# target/debug/rig).

set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
refdir="$here/website/reference"

RIG="${1:-}"
if [ -z "$RIG" ]; then
  if [ -x "$here/target/release/rig" ]; then
    RIG="$here/target/release/rig"
  elif [ -x "$here/target/debug/rig" ]; then
    RIG="$here/target/debug/rig"
  else
    echo "error: no rig binary found; run 'cargo build --release' or pass a path" >&2
    exit 1
  fi
fi

MARKER='<!-- Generated by website/gen-cli-reference.sh. Do not edit by hand. -->'

# Make help output deterministic and free of ANSI colour.
export NO_COLOR=1
export TERM=dumb

# List the (non-help) subcommand names from a command's --help output. The
# names live in the "Commands:" block, indented, first whitespace-delimited
# token per line, terminated by a blank line.
subcommands() {
  "$RIG" "$@" --help 2>&1 |
    awk '
      /^Commands:/ { incmd = 1; next }
      incmd && /^[[:space:]]*$/ { incmd = 0 }
      incmd && /^[[:space:]]+[^[:space:]]/ { print $1 }
    ' |
    grep -vx 'help' || true
}

# Emit a Markdown section (to stdout) for the given command path and all of
# its subcommands. $1 = header depth (number of leading #), rest = command
# path (relative to `rig`).
emit() {
  local depth="$1"; shift
  local hashes
  hashes="$(printf '%.0s#' $(seq 1 "$depth"))"
  local title="rig${*:+ $*}"

  printf '%s `%s`\n\n' "$hashes" "$title"
  printf '```text\n'
  "$RIG" "$@" --help 2>&1
  printf '```\n\n'

  local sub
  for sub in $(subcommands "$@"); do
    emit "$((depth + 1))" "$@" "$sub"
  done
}

# Remove previously generated pages and includes.
for f in "$refdir"/*.qmd; do
  [ -e "$f" ] || continue
  if head -n 5 "$f" | grep -qF "$MARKER"; then
    rm "$f"
  fi
done
rm -f "$refdir/_overview.md" "$refdir/_toc.md"

# Top-level overview (rig --help only, no recursion).
{
  printf '%s\n\n' "$MARKER"
  printf '## `rig`\n\n'
  printf '```text\n'
  "$RIG" --help 2>&1
  printf '```\n'
} >"$refdir/_overview.md"

# One page per top-level command, plus the linked table of contents.
: >"$refdir/_toc.md"
printf '%s\n\n' "$MARKER" >>"$refdir/_toc.md"

"$RIG" --help 2>&1 |
  awk '
    /^Commands:/ { incmd = 1; next }
    incmd && /^[[:space:]]*$/ { incmd = 0 }
    incmd && /^[[:space:]]+[^[:space:]]/ {
      name = $1
      $1 = ""
      sub(/^[[:space:]]+/, "")
      print name "\t" $0
    }
  ' |
  grep -v $'^help\t' |
  while IFS=$'\t' read -r name desc; do
    {
      printf -- '---\ntitle: "rig %s"\n---\n\n' "$name"
      printf '%s\n\n' "$MARKER"
      emit 2 "$name"
    } >"$refdir/$name.qmd"

    printf -- '- [`rig %s`](%s.qmd) — %s\n' "$name" "$name" "$desc" >>"$refdir/_toc.md"
  done

echo "wrote per-command pages, _overview.md and _toc.md in $refdir"
