use std::collections::HashMap;

use once_cell::sync::Lazy;
use serde::{Deserialize, Serialize};
#[cfg(target_os = "windows")]
use serde_json::Value;

use crate::repos::Repository;

pub static HC_REPOS: Lazy<Vec<Repository>> = Lazy::new(|| {
    let data = include_str!("data/repos.json");
    serde_json::from_str(data).expect("Invalid JSON in data/repos.json")
});

pub static HC_PROFILE_REPOS: Lazy<String> = Lazy::new(|| {
    let data = include_str!("data/repositories.R");
    // Normalize line endings. The embedded file may be checked out with CRLF
    // (e.g. on Windows without a .gitattributes rule), but we always write and
    // match the profile with LF-terminated lines.
    data.replace("\r\n", "\n")
});

// The files of the `rvenv` shim R package that `rig proj init` seeds into a
// project's `.rvenvlib/rvenv`, see `write_shim_package()` in
// `src/rvenv.rs`. `NAMESPACE`, `LICENSE` and the R code are the package source
// verbatim; `DESCRIPTION` and `Meta/package.rds` are what an install adds, and
// are generated by `cargo xtask gen-rvenv-shim` (see that module for why they
// are generated and committed rather than built on the user's machine).
pub static HC_RVENV_PKG_NAMESPACE: &str = include_str!("data/rvenv-pkg/NAMESPACE");
pub static HC_RVENV_PKG_LICENSE: &str = include_str!("data/rvenv-pkg/LICENSE");
pub static HC_RVENV_PKG_CODE: &str = include_str!("data/rvenv-pkg/R/rvenv.R");
pub static HC_RVENV_PKG_DESCRIPTION: &str = include_str!("data/rvenv-shim/DESCRIPTION");
pub static HC_RVENV_PKG_META: &[u8] = include_bytes!("data/rvenv-shim/package.rds");

pub struct ProfileReposMarkers {
    pub generic_start: String,
    pub current_start: String,
    pub end: String,
}

pub static HC_PROFILE_REPOS_MARKERS: Lazy<ProfileReposMarkers> = Lazy::new(|| {
    let data = include_str!("data/repositories.R");
    // Use `lines()` (not `split('\n')`) so a CRLF checkout of the embedded file
    // does not leave stray '\r' on the markers. Those markers are matched as
    // regexes against `read_lines()` output, which is always CR-stripped, so a
    // trailing '\r' here would make them never match and break profile parsing.
    let lines = data.trim().lines().collect::<Vec<&str>>();
    ProfileReposMarkers {
        generic_start: lines[0].to_string(),
        current_start: lines[1].to_string(),
        end: lines[lines.len() - 1].to_string(),
    }
});

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BiocVersionMapping {
    pub r_version: String,
    pub bioc_version: String,
    /// `YYYY-MM-DD`, `None` for a release that is still in development.
    #[serde(default)]
    pub release_date: Option<String>,
}

/// Every Bioconductor release, oldest first, with the R minor version it
/// belongs to. Recent R minor versions have two Bioconductor releases.
pub static HC_BIOC_VERSIONS: Lazy<Vec<BiocVersionMapping>> = Lazy::new(|| {
    let data = include_str!("data/r-version-to-bioc-version.json");
    serde_json::from_str(data).expect("Invalid JSON in data/r-version-to-bioc-version.json")
});

#[allow(dead_code)]
pub static HC_BIOC_VERSION_TO_R_VERSION: Lazy<HashMap<String, String>> = Lazy::new(|| {
    HC_BIOC_VERSIONS
        .iter()
        .map(|m| (m.bioc_version.clone(), m.r_version.clone()))
        .collect()
});

#[cfg(target_os = "windows")]
pub static HC_RTOOLS_AARCH64: Lazy<Value> = Lazy::new(|| {
    let data = include_str!("data/rtools-versions-aarch64.json");
    serde_json::from_str(data).expect("Invalid JSON in data/rtools-versions-aarch64.json")
});

#[cfg(target_os = "windows")]
pub static HC_RTOOLS: Lazy<Value> = Lazy::new(|| {
    let data = include_str!("data/rtools-versions.json");
    serde_json::from_str(data).expect("Invalid JSON in data/rtools-versions.json")
});
