name: Build rig containers for new release

on:
  workflow_dispatch:
    inputs:
      inpconts:
        description: |
          Containers, comma separated list or 'all'.
        required: false
        default: 'devel'
        type: string
  push:
  schedule:
    - cron:  '55 7 * * *'

jobs:

  # ------------------------------------------------------------------------

  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      containers: ${{ steps.setup-matrix.outputs.containers }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up matrix of containers
      id: setup-matrix
      run: |
        cs=$(python containers/matrix.py ${{ github.event.inputs.inpconts || 'devel' }})
        echo "containers=$cs" >> $GITHUB_OUTPUT

  # ------------------------------------------------------------------------

  amd64:
    needs: setup-matrix
    strategy:
      fail-fast: false
      matrix:
        config: ${{ fromJson(needs.setup-matrix.outputs.containers) }}
    uses: ./.github/workflows/conts-workflow.yml
    with:
      config: "${{ toJSON(matrix.config) }}"
      platform: amd64
      runs-on: ubuntu-latest
    secrets: inherit

  arm64:
    needs: setup-matrix
    strategy:
      fail-fast: false
      matrix:
        config: ${{ fromJson(needs.setup-matrix.outputs.containers) }}
    uses: ./.github/workflows/conts-workflow.yml
    with:
      config: "${{ toJSON(matrix.config) }}"
      platform: arm64
      runs-on: ubuntu-24.04-arm
    secrets: inherit

  manifest:
    needs: [ setup-matrix, amd64, arm64 ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config: ${{ fromJson(needs.setup-matrix.outputs.containers) }}
    steps:
      - uses: int128/docker-manifest-create-action@v2
        id: build
        with:
          push: true
          tags: "${{ join(matrix.config.tags, '\n') }}"
          sources: |
            "ghcr.io/r-lib/rig/${{ matrix.config.name }}-amd64:latest"
            "ghcr.io/r-lib/rig/${{ matrix.config.name }}-arm64:latest"
