name: Reusable container build workflow

on:
  workflow_call:
    inputs:
      platform:
        description: Docker Linux platform to use, e.g. amd64.
        type: string
        required: true
      runs-on:
        description: GitHub Actions runner to use, e.g. ubuntu-latest.
        type: string
        required: true
      config:
        description: Matrix config.
        type: string
        required: true
    outputs:
      image-uri:
        description: Image URI
        value: ${{ jobs.build.outputs.image-uri }}

jobs:
  build:
    runs-on: ${{ inputs.runs-on }}
    name: ${{ fromJSON(inputs.config).name }}
    outputs:
      image-uri: "ghcr.io/r-lib/rig/${{ fromJSON(inputs.config).name}}-${{ inputs.platform }}:latest"

    steps:
    - uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build
      uses: docker/build-push-action@v5
      with:
        platforms: linux/${{ inputs.platform }}
        provenance: false
        context: containers/${{ fromJSON(inputs.config).dir }}
        file: ${{ fromJSON(inputs.config).file }}
        build-args: "${{ join(fromJSON(inputs.config).args, '\n') }}"
        push: true
        outputs:
        tags: "ghcr.io/r-lib/rig/${{ fromJSON(inputs.config).name }}-${{ inputs.platform }}:latest"
